version: '3.3'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USER_NAME}
      WORDPRESS_DB_PASSWORD: ${USER_PASSWD}
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASSWD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: